# Generated by Django 2.0.5 on 2018-05-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='submission_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
